name: idea_sharing_rooms

description: >
  Idea Sharing + Real-Time Group Rooms Flutter app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  # Encryption and security
  encrypt: ^5.0.1
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  # UUID generation
  uuid: ^4.1.0
  # Optional: image_picker for adding image URLs via camera/gallery
  # TODO: Add real-time backend package (SpacetimeDB/Ably/Socket.io/etc when logic settled)


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  # TODO: Add linting and formatting packages

flutter:
  uses-material-design: true
